# """
# Unified IFC exporter for Flurstueck, Baugrenze, and Baulinie
# """
# import ifcopenshell
# from ifcopenshell.guid import new as new_guid
# import time

# from Xplan2IFC import main, IFCFloorplanGenerator

# def create_ifc_project(schema="IFC4X3_ADD2"):
#     ifc = ifcopenshell.file(schema=schema)

#     ifc.header.file_description.description = (
#         "ViewDefinition [ReferenceView]",
#     )
#     ifc.header.file_description.implementation_level = "2;1"
#     ifc.header.file_name.originating_system = (
#         "RWTHAachen - Python IFC Exporter - 1.0.0"
#     )
#     ifc.header.file_name.preprocessor_version = "IfcOpenShell 0.7.0"
#     ifc.header.file_name.authorization = "Generated by Python script"

#     org = ifc.create_entity("IfcOrganization", Name="RWTHAachen")
#     app = ifc.create_entity(
#         "IfcApplication",
#         ApplicationDeveloper=org,
#         Version="1.0.0",
#         ApplicationFullName="City2IFCtranformer",
#         ApplicationIdentifier="3DSitePlane"
#     )

#     person = ifc.create_entity("IfcPerson", FamilyName="Ahmad", GivenName="Fatma")
#     po = ifc.create_entity(
#     "IfcPersonAndOrganization",
#     ThePerson=person,
#     TheOrganization=org)
#     owner_hist = ifc.create_entity(
#         "IfcOwnerHistory",
#         OwningUser=po,
#         OwningApplication=app,
#         State="READWRITE",
#         ChangeAction="ADDED",
#         LastModifiedDate=int(time.time()),
#         CreationDate=int(time.time())
#     )

#     length_unit = ifc.create_entity("IfcSIUnit", UnitType="LENGTHUNIT", Name="METRE")
#     area_unit = ifc.create_entity("IfcSIUnit", UnitType="AREAUNIT", Name="SQUARE_METRE")
#     volume_unit = ifc.create_entity("IfcSIUnit", UnitType="VOLUMEUNIT", Name="CUBIC_METRE")
#     angle_unit = ifc.create_entity("IfcSIUnit", UnitType="PLANEANGLEUNIT", Name="RADIAN")

#     units = ifc.create_entity(
#         "IfcUnitAssignment",
#         Units=[length_unit, area_unit, volume_unit, angle_unit]
#     )


#     origin = ifc.create_entity("IfcCartesianPoint", [0.0, 0.0, 0.0])
#     placement = ifc.create_entity("IfcAxis2Placement3D", Location=origin)
#     context = ifc.create_entity(
#         "IfcGeometricRepresentationContext",
#         ContextIdentifier="Body",
#         ContextType="Model",
#         CoordinateSpaceDimension=3,
#         Precision=0.01,
#         WorldCoordinateSystem=placement
#     )
#     subcontext_2D = ifc.create_entity(
#         "IfcGeometricRepresentationSubContext",
#         ContextIdentifier="Body-Fallback",
#         ContextType="Model",
#         ParentContext=context,
#         TargetScale=1.0,
#         TargetView="PLAN_VIEW"
#     )
#     project = ifc.create_entity(
#         "IfcProject",
#         GlobalId=new_guid(),
#         Name="SitePlan3D",
#         RepresentationContexts=[context],
#         UnitsInContext=units,
#         OwnerHistory=owner_hist
#     )
#     map_unit = length_unit 
#     crs = ifc.create_entity(
#         "IfcProjectedCRS",
#         Name="Local CRS",
#         Description="Local BIM CRS",
#         GeodeticDatum=None,
#         VerticalDatum=None,
#         MapProjection=None,
#         MapZone=None,
#         MapUnit=map_unit
#     )
#     ifc.create_entity(
#         "IfcMapConversion",
#         SourceCRS=context,
#         TargetCRS=crs,
#         Eastings=0.0,
#         Northings=0.0, 
#         OrthogonalHeight=0.0
#     )

#     site_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
#     site = ifc.create_entity("IfcSite", GlobalId=new_guid(), Name="PlanningSite", ObjectPlacement=site_placement)
#     building_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
#     building = ifc.create_entity("IfcBuilding", GlobalId=new_guid(),OwnerHistory=owner_hist, Name="Planned_Building", ObjectPlacement=building_placement)
#     storey_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
#     storey = ifc.create_entity("IfcBuildingStorey", GlobalId=new_guid(),OwnerHistory=owner_hist, Name="level_1", ObjectPlacement=storey_placement)

#     ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=project, RelatedObjects=[site])
#     ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=site, RelatedObjects=[building])
#     ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=building, RelatedObjects=[storey])

#     return ifc, context, project, site, building, storey

# def create_fill_style(ifc, target_entity=None):
#     yellow = ifc.create_entity("IfcColourRgb", Red=1.0, Green=1.0, Blue=0.0)
#     curve_font = ifc.create_entity("IfcDraughtingPreDefinedCurveFont", Name="continuous")
#     curve_style = ifc.create_entity("IfcCurveStyle", CurveFont=curve_font, CurveWidth=None, CurveColour=yellow)
#     hatch_spacing = ifc.create_entity("IfcPositiveLengthMeasure", 1000.0)
#     fill_hatching = ifc.create_entity(
#         "IfcFillAreaStyleHatching",
#         HatchLineAppearance=curve_style,
#         StartOfNextHatchLine=hatch_spacing,
#         HatchLineAngle=45.0
#     )
#     fill_style = ifc.create_entity("IfcFillAreaStyle", Name="FillStyle", FillStyles=[fill_hatching])
#     if target_entity:
#         ifc.create_entity("IfcStyledItem", Item=target_entity, Styles=[fill_style])
#     return fill_style

# def create_annotation(ifc, points, context, site, name="Annotation", fill_style=None):
#     """
#     Creates a 2D annotation fill area.
#     Removes the last point if it duplicates the first point to avoid GEM111 errors.
#     """
#     if len(points) < 3:
#         return None
#     if points[0] == points[-1]:
#         points = points[:-1]

#     ifc_points = [
#         ifc.create_entity("IfcCartesianPoint", Coordinates=[float(c) for c in pt])
#         for pt in points
#     ]
#     ifc_points.append(ifc_points[0])

#     polyline = ifc.create_entity("IfcPolyline", Points=ifc_points)
#     fill_area = ifc.create_entity("IfcAnnotationFillArea", OuterBoundary=polyline)
#     if fill_style is not None:
#         ifc.create_entity("IfcStyledItem", Item=fill_area, Styles=[fill_style])
#     shape = ifc.create_entity(
#         "IfcShapeRepresentation",
#         ContextOfItems=context,
#         RepresentationIdentifier="Annotation",
#         RepresentationType="Annotation2D",
#         Items=[fill_area]
#     )
#     prod_def = ifc.create_entity("IfcProductDefinitionShape", Representations=[shape])
#     annotation = ifc.create_entity(
#         "IfcAnnotation",
#         GlobalId=new_guid(),
#         Name=name,
#         ObjectPlacement=site.ObjectPlacement,
#         Representation=prod_def
#     )
#     ifc.create_entity(
#         "IfcRelContainedInSpatialStructure",
#         GlobalId=new_guid(),
#         RelatingStructure=site,
#         RelatedElements=[annotation]
#     )

# def create_virtual_element(ifc, points, context, storey, name="VirtualElement"):
#     if len(points) < 3:
#         return None
#     seen = set()
#     cleaned_pts = []
#     for pt in points:
#         key = tuple(round(c, 6) for c in pt)
#         if key not in seen:
#             cleaned_pts.append(pt)
#             seen.add(key)

#     if len(cleaned_pts) < 3:
#         return None
#     ifc_points = [ifc.create_entity("IfcCartesianPoint", Coordinates=[float(c) for c in pt])
#                   for pt in cleaned_pts]
#     polyloop = ifc.create_entity("IfcPolyLoop", Polygon=ifc_points)
#     outer_bound = ifc.create_entity("IfcFaceOuterBound", Bound=polyloop, Orientation=True)
#     face = ifc.create_entity("IfcFace", Bounds=[outer_bound])
#     cfs = ifc.create_entity("IfcConnectedFaceSet", CfsFaces=[face])
#     surface_model = ifc.create_entity("IfcFaceBasedSurfaceModel", FbsmFaces=[cfs])
#     shape_rep = ifc.create_entity(
#         "IfcShapeRepresentation",
#         ContextOfItems=context,
#         RepresentationIdentifier="Body",
#         RepresentationType="SurfaceModel",
#         Items=[surface_model]
#     )
#     prod_def = ifc.create_entity("IfcProductDefinitionShape", Representations=[shape_rep])
#     virtual = ifc.create_entity(
#         "IfcAnnotation",
#         GlobalId=new_guid(),
#         Name=name,
#         ObjectPlacement=storey.ObjectPlacement,
#         Representation=prod_def
#     )
#     ifc.create_entity(
#         "IfcRelContainedInSpatialStructure",
#         GlobalId=new_guid(),
#         RelatingStructure=storey,
#         RelatedElements=[virtual]
#     )

# def export_ifc(filename="project_site_building.ifc"):
#     ifc, context, project, site, building, storey = create_ifc_project()
#     fill_style = create_fill_style(ifc)
#     data = main()
#     flurstueck_dict = data.get("flurstueck_dict", {})
#     baugrenze_dict = data.get("baugrenze_dict", {})
#     baulinie_dict = data.get("baulinie_dict", {})
#     for key, item in flurstueck_dict.items():
#         create_annotation(ifc, item["points"], context, site, name=item.get("name", f"FS{key}"), fill_style=fill_style)
    
#     Z_min, Z_max = 0, 12
#     for geom_dict, label in [(baugrenze_dict, "BG"), (baulinie_dict, "BL")]:
#         for key, item in geom_dict.items():
#             points = item["points"]
#             name = item.get("name", f"{label}_{key}")
#             for i in range(len(points) - 1):
#                 p1, p2 = points[i], points[i + 1]
#                 face_pts = [
#                     (p1[0], p1[1], Z_min),
#                     (p2[0], p2[1], Z_min),
#                     (p2[0], p2[1], Z_max),
#                     (p1[0], p1[1], Z_max)
#                 ]
#                 unique_pts = []
#                 for pt in face_pts:
#                     if not unique_pts or pt != unique_pts[-1]:
#                         unique_pts.append(pt)
#                 if len(unique_pts) >= 3:
#                     create_virtual_element(ifc, unique_pts, context, storey, name=f"{name}_face_{i+1}")
#     ifc.write(filename)
#     print(f"IFC saved: {filename}")
# if __name__ == "__main__":
#     export_ifc()
"""
Unified IFC exporter for Flurstueck, Baugrenze, and Baulinie
"""
import ifcopenshell
from ifcopenshell.guid import new as new_guid
import time

from Xplan2IFC import main, IFCFloorplanGenerator

def create_ifc_project(schema="IFC4X3_ADD2"):
    ifc = ifcopenshell.file(schema=schema)

    ifc.header.file_description.description = ("ViewDefinition [ReferenceView]",)
    ifc.header.file_description.implementation_level = "2;1"
    ifc.header.file_name.originating_system = "RWTHAachen - Python IFC Exporter - 1.0.0"
    ifc.header.file_name.preprocessor_version = "IfcOpenShell 0.7.0"
    ifc.header.file_name.authorization = "Generated by Python script"

    org = ifc.create_entity("IfcOrganization", Name="RWTHAachen")
    app = ifc.create_entity(
        "IfcApplication",
        ApplicationDeveloper=org,
        Version="1.0.0",
        ApplicationFullName="City2IFCtranformer",
        ApplicationIdentifier="3DSitePlane"
    )

    person = ifc.create_entity("IfcPerson", FamilyName="Ahmad", GivenName="Fatma")
    po = ifc.create_entity("IfcPersonAndOrganization", ThePerson=person, TheOrganization=org)
    owner_hist = ifc.create_entity(
        "IfcOwnerHistory",
        OwningUser=po,
        OwningApplication=app,
        State="READWRITE",
        ChangeAction="ADDED",
        LastModifiedDate=int(time.time()),
        CreationDate=int(time.time())
    )

    length_unit = ifc.create_entity("IfcSIUnit", UnitType="LENGTHUNIT", Name="METRE")
    area_unit = ifc.create_entity("IfcSIUnit", UnitType="AREAUNIT", Name="SQUARE_METRE")
    volume_unit = ifc.create_entity("IfcSIUnit", UnitType="VOLUMEUNIT", Name="CUBIC_METRE")
    angle_unit = ifc.create_entity("IfcSIUnit", UnitType="PLANEANGLEUNIT", Name="RADIAN")

    units = ifc.create_entity(
        "IfcUnitAssignment",
        Units=[length_unit, area_unit, volume_unit, angle_unit]
    )

    origin = ifc.create_entity("IfcCartesianPoint", [0.0, 0.0, 0.0])
    placement = ifc.create_entity("IfcAxis2Placement3D", Location=origin)
    context = ifc.create_entity(
        "IfcGeometricRepresentationContext",
        ContextIdentifier="Body",
        ContextType="Model",
        CoordinateSpaceDimension=3,
        Precision=0.01,
        WorldCoordinateSystem=placement
    )
    subcontext_2D = ifc.create_entity(
        "IfcGeometricRepresentationSubContext",
        ContextIdentifier="Body-Fallback",
        ContextType="Model",
        ParentContext=context,
        TargetScale=1.0,
        TargetView="PLAN_VIEW"
    )
    project = ifc.create_entity(
        "IfcProject",
        GlobalId=new_guid(),
        Name="SitePlan3D",
        RepresentationContexts=[context],
        UnitsInContext=units,
        OwnerHistory=owner_hist
    )
    map_unit = length_unit 
    crs = ifc.create_entity(
        "IfcProjectedCRS",
        Name="Local CRS",
        Description="Local BIM CRS",
        GeodeticDatum=None,
        VerticalDatum=None,
        MapProjection=None,
        MapZone=None,
        MapUnit=map_unit
    )
    ifc.create_entity(
        "IfcMapConversion",
        SourceCRS=context,
        TargetCRS=crs,
        Eastings=0.0,
        Northings=0.0, 
        OrthogonalHeight=0.0
    )

    site_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
    site = ifc.create_entity("IfcSite", GlobalId=new_guid(), Name="PlanningSite", ObjectPlacement=site_placement)
    building_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
    building = ifc.create_entity("IfcBuilding", GlobalId=new_guid(), OwnerHistory=owner_hist, Name="Planned_Building", ObjectPlacement=building_placement)
    storey_placement = ifc.create_entity("IfcLocalPlacement", RelativePlacement=placement)
    storey = ifc.create_entity("IfcBuildingStorey", GlobalId=new_guid(), OwnerHistory=owner_hist, Name="level_1", ObjectPlacement=storey_placement)

    ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=project, RelatedObjects=[site])
    ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=site, RelatedObjects=[building])
    ifc.create_entity("IfcRelAggregates", GlobalId=new_guid(), RelatingObject=building, RelatedObjects=[storey])

    return ifc, context, project, site, building, storey
def create_site_solid(ifc, points, context, site, height=12.0):
    if len(points) < 3:
        return None

    if points[0] == points[-1]:
        points = points[:-1]

    bottom_points = [(pt[0], pt[1], 0.0) for pt in points]
    top_points = [(pt[0], pt[1], height) for pt in points]

    def create_ifc_points(pt_list):
        return [ifc.create_entity("IfcCartesianPoint", Coordinates=tuple(float(c) for c in pt))
                for pt in pt_list]

    # bottom face
    bottom_face = ifc.create_entity(
        "IfcFace",
        Bounds=[ifc.create_entity(
            "IfcFaceOuterBound",
            Bound=ifc.create_entity("IfcPolyLoop", Polygon=create_ifc_points(bottom_points)),
            Orientation=True
        )]
    )

    # top face
    top_face = ifc.create_entity(
        "IfcFace",
        Bounds=[ifc.create_entity(
            "IfcFaceOuterBound",
            Bound=ifc.create_entity("IfcPolyLoop", Polygon=create_ifc_points(top_points)),
            Orientation=True
        )]
    )

    # side faces
    side_faces = []
    n = len(points)
    for i in range(n):
        p1b, p2b = bottom_points[i], bottom_points[(i + 1) % n]
        p1t, p2t = top_points[i], top_points[(i + 1) % n]
        side_face_points = [p1b, p2b, p2t, p1t]

        side_face = ifc.create_entity(
            "IfcFace",
            Bounds=[ifc.create_entity(
                "IfcFaceOuterBound",
                Bound=ifc.create_entity("IfcPolyLoop", Polygon=create_ifc_points(side_face_points)),
                Orientation=True
            )]
        )
        side_faces.append(side_face)

    all_faces = [bottom_face, top_face] + side_faces
    cfs = ifc.create_entity("IfcConnectedFaceSet", CfsFaces=all_faces)
    surface_model = ifc.create_entity("IfcFaceBasedSurfaceModel", FbsmFaces=[cfs])

    shape_rep = ifc.create_entity(
        "IfcShapeRepresentation",
        ContextOfItems=context,
        RepresentationIdentifier="Footprint",
        RepresentationType="SurfaceModel",
        Items=[surface_model]
    )
    prod_def = ifc.create_entity("IfcProductDefinitionShape", Representations=[shape_rep])
    site.Representation = prod_def

def create_fill_style(ifc):
    """Creates a yellow diagonal hatch fill style."""
    yellow = ifc.create_entity("IfcColourRgb", Red=1.0, Green=1.0, Blue=0.0)
    curve_font = ifc.create_entity("IfcDraughtingPreDefinedCurveFont", Name="continuous")
    curve_style = ifc.create_entity("IfcCurveStyle", CurveFont=curve_font, CurveWidth=None, CurveColour=yellow)
    hatch_spacing = ifc.create_entity("IfcPositiveLengthMeasure", 1000.0)
    fill_hatching = ifc.create_entity(
        "IfcFillAreaStyleHatching",
        HatchLineAppearance=curve_style,
        StartOfNextHatchLine=hatch_spacing,
        HatchLineAngle=45.0
    )
    fill_style = ifc.create_entity("IfcFillAreaStyle", Name="FillStyle", FillStyles=[fill_hatching])
    return fill_style

def create_site_fill_area(ifc, points, fill_style=None):
    """Creates a fill area for the site polygon and attaches the fill style."""
    if len(points) < 3:
        return None
    if points[0] == points[-1]:
        points = points[:-1]

    ifc_points = [ifc.create_entity("IfcCartesianPoint", Coordinates=[float(c) for c in pt]) for pt in points]
    ifc_points.append(ifc_points[0])  # close the loop

    polyline = ifc.create_entity("IfcPolyline", Points=ifc_points)
    fill_area = ifc.create_entity("IfcAnnotationFillArea", OuterBoundary=polyline)
    if fill_style:
        ifc.create_entity("IfcStyledItem", Item=fill_area, Styles=[fill_style])
    return fill_area

def create_virtual_element(ifc, points, context, storey, name="VirtualElement"):
    """Creates 3D virtual walls or lines (baugrenze/baulinie)."""
    if len(points) < 3:
        return None
    seen = set()
    cleaned_pts = []
    for pt in points:
        key = tuple(round(c, 6) for c in pt)
        if key not in seen:
            cleaned_pts.append(pt)
            seen.add(key)
    if len(cleaned_pts) < 3:
        return None

    ifc_points = [ifc.create_entity("IfcCartesianPoint", Coordinates=[float(c) for c in pt])
                  for pt in cleaned_pts]
    polyloop = ifc.create_entity("IfcPolyLoop", Polygon=ifc_points)
    outer_bound = ifc.create_entity("IfcFaceOuterBound", Bound=polyloop, Orientation=True)
    face = ifc.create_entity("IfcFace", Bounds=[outer_bound])
    cfs = ifc.create_entity("IfcConnectedFaceSet", CfsFaces=[face])
    surface_model = ifc.create_entity("IfcFaceBasedSurfaceModel", FbsmFaces=[cfs])
    shape_rep = ifc.create_entity(
        "IfcShapeRepresentation",
        ContextOfItems=context,
        RepresentationIdentifier="Body",
        RepresentationType="SurfaceModel",
        Items=[surface_model]
    )
    prod_def = ifc.create_entity("IfcProductDefinitionShape", Representations=[shape_rep])
    virtual = ifc.create_entity(
        "IfcAnnotation",
        GlobalId=new_guid(),
        Name=name,
        ObjectPlacement=storey.ObjectPlacement,
        Representation=prod_def
    )
    ifc.create_entity(
        "IfcRelContainedInSpatialStructure",
        GlobalId=new_guid(),
        RelatingStructure=storey,
        RelatedElements=[virtual]
    )

def export_ifc(filename="siteF_BBBL.ifc"):
    ifc, context, project, site, building, storey = create_ifc_project()
    fill_style = create_fill_style(ifc)

    # Load polygon data
    data = main()
    flurstueck_dict = data.get("flurstueck_dict", {})
    baugrenze_dict = data.get("baugrenze_dict", {})
    baulinie_dict = data.get("baulinie_dict", {})

    all_points = []
    for item in flurstueck_dict.values():
        all_points.extend(item["points"])

    if all_points:
        create_site_solid(ifc, all_points, context, site)

    # Create 3D baugrenze/baulinie
    Z_min, Z_max = 0, 12
    for geom_dict, label in [(baugrenze_dict, "BG"), (baulinie_dict, "BL")]:
        for key, item in geom_dict.items():
            points = item["points"]
            name = item.get("name", f"{label}_{key}")
            for i in range(len(points) - 1):
                p1, p2 = points[i], points[i + 1]
                face_pts = [
                    (p1[0], p1[1], Z_min),
                    (p2[0], p2[1], Z_min),
                    (p2[0], p2[1], Z_max),
                    (p1[0], p1[1], Z_max)
                ]
                unique_pts = []
                for pt in face_pts:
                    if not unique_pts or pt != unique_pts[-1]:
                        unique_pts.append(pt)
                if len(unique_pts) >= 3:
                    create_virtual_element(ifc, unique_pts, context, storey, name=f"{name}_face_{i+1}")

    # Save IFC
    ifc.write(filename)
    print(f"IFC saved: {filename}")

if __name__ == "__main__":
    export_ifc()
